name: "infra terraform plan & apply"

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 10_infra/**
      - .github/workflows/10_infra_**

env:
  AWS_REGION: ap-northeast-1
  TF_VERSION: 1.4.4

jobs:
  pre-run:
    name: Pre-Run
    runs-on: ubuntu-latest
    steps:
      - name: Branch Check
        id: branch_check
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "ENV_NAME=prod" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref_name }}" == "develop" ]; then
            echo "ENV_NAME=dev" >> $GITHUB_OUTPUT
          else
            echo "ENV_NAME=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi
    outputs:
      env_name: ${{ steps.branch_check.outputs.ENV_NAME }}

  terraform-apply:
    name: Terraform-Apply
    needs: pre-run
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: "10_infra"
    environment:
      name: ${{ needs.pre-run.outputs.env_name }}
    env:
      DEPLOY_ENV: ${{ needs.pre-run.outputs.env_name }}
      AWS_REGION: ap-northeast-1
      TF_VERSION: 1.4.4
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: Configure AWS Credential
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
      - name: Terraform init
        run: |
          terraform init \
            -backend-config=./tfbackend/${{ env.DEPLOY_ENV }}.tfbackend \
            -no-color
      - name: Terraform apply
        id: apply
        run: |
          terraform apply \
            -var-file=./tfvars/${{ env.DEPLOY_ENV }}.tfvars \
            -var 'username=${{ secrets.MYSQL_USERNAME }}' \
            -var 'password=${{ secrets.MYSQL_PASSWORD }}' \
            -input=false \
            -no-color \
            -auto-approve
